name: storybook_flutter_example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  flutter:
    sdk: flutter
  storybook_flutter:
    path: ..
  universal_html: ^2.0.8

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mews_pedantic: ^0.20.0

flutter:
  uses-material-design: true
