name: storybook_flutter_example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^12.1.1
  storybook_flutter:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  mews_pedantic: ^0.20.0

flutter:
  uses-material-design: true
  assets:
    - assets/code_snippets/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/RobotoMono-Regular.ttf